### ISSUE TITLE
FontForge Source Files

### ISSUE THREAD

**Issue by alexeiva** [ossobuffo/jura#1]
I downloaded the new FontForge, and it crashes on start (Mac OS 10.10.5). 
@davelab6, @kalapi: could you help me port this project into Glyphs or UFO, 
and push them here: https://github.com/FontsToRaisins/jura/tree/master?

**Comment by ossobuffo** [comment]
Did you try installing FontForge with homebrew? That works for me.

**Comment by alexeiva** [comment]
@davelab6 helped me install sfd2ufo to export into UFO, and in the process trufont was installed to fix the required missing defcon library. 
Works now, thanks.

**Comment by davelab6** [comment]
Used https://github.com/khaledhosny/sfd2ufo
