### ISSUE TITLE
Interpolation?

### ISSUE THREAD

**Issue by alexeiva** [ossobuffo/jura#2]
Hi Daniel,

I have a few questions: I am assuming you used interpolation to build the 4 weights, 
with Light, and Semi-Bold being the extremes, is that right?

To speed up the improvements it would make sense for me to adjust the extreme masters, and 
interpolate the middle instances. I have tried doing this. But the UFO sources are in TrueType format. When I convert them to PS outlines, they aren't longer compatible. This may have be caused due to contour conversion. 

Do you happen to have a post-script-outlines version of the masters in UFO/SFD format?

**Comment by ossobuffo** [comment]
I don't. I started with the Light weight and used FontForge's "adjust weight" function, then did manual tweaks. I didn't have access to interpolation automation at the time, and even if I had, I was too ignorant to be aware of it.

You might have a look at some of the older tarballs here:
http://danieljohnson.name/fonts/jura
There may be some cubic-spline fonts in the history. I'm not sure. Most of the historical adjustments were either to kerning/spacing or just adding composite glyphs. You are probably best off just converting quadratic splines to cubic and dealing with the fallout.

Once again, apologies for my banging sticks and rocks together.

**Comment by alexeiva** [comment]
No, problem. Thank you. This information is very useful.
