### ISSUE TITLE
Smallcap glyphs

### ISSUE THREAD

**Issue by m4rc1e** [ossobuffo/jura#4]
Hey @ossobuffo,

We noticed the original release has a set of smallcap vowels.

![screen shot 2017-03-07 at 14 16 05](https://cloud.githubusercontent.com/assets/7525512/23660254/b88c7104-0340-11e7-8471-900358a7b003.png)

They have been encoded to puas and are not in any OT feature.

Should we still include these?

cc @alexeiva @davelab6

**Comment by ossobuffo** [comment]
I am trying to remember what these were for. They were created for composing glyphs with stacked diacritics, perhaps Vietnamese? I can't imagine any reason to keep them at this point unless we wanted to do a full small-caps set.

**Comment by m4rc1e** [comment]
Thanks for the explanation.

Do you mind if we leave them out in our [update](https://github.com/alexeiva/jura)? 

We've been improving Jura for the past few months now and its shaping up nicely. 

If you don't mind us leaving them out, I'll send you a pr.

**Comment by ossobuffo** [comment]
Make it so.

**Comment by m4rc1e** [comment]
Thank you! I'll close this as well
